---
- name: Security and init setup
  hosts: all
  gather_facts: no
  tasks:
    - name: Change ssh port
      ansible.builtin.import_tasks: tasks/ssh.yaml
    - name: Setup security
      ansible.builtin.import_tasks: tasks/security.yaml

- name: Setup calendar
  hosts: calendar
  tasks:
    - ansible.builtin.import_tasks: tasks/calendar.yaml

- name: Setup informabot
  hosts: bot
  tasks:
    - ansible.builtin.import_tasks: tasks/bot.yaml

- name: Setup dynamik
  hosts: dynamik
  tasks:
    - ansible.builtin.import_tasks: tasks/dynamik.yaml

- name: Setup fileseeker
  hosts: fileseeker
  tasks:
    - ansible.builtin.import_tasks: tasks/fileseeker.yaml
