---
# - name: Security and init setup
#   hosts: all
#   gather_facts: no
#   tasks:
#     - name: Change ssh port
#       ansible.builtin.import_tasks: tasks/ssh.yaml
#     - name: Ufw
#       ansible.builtin.import_tasks: tasks/ufw.yaml

- name: Setup calendar
  hosts: calendar
  tasks:
    - ansible.builtin.import_tasks: tasks/calendar.yaml

- name: Setup informabot
  hosts: bot
  tasks:
    - ansible.builtin.import_tasks: tasks/bot.yaml

- name: Setup dynamik
  hosts: dynamik
  tasks:
    - ansible.builtin.import_tasks: tasks/dynamik.yaml

- name: Setup dynamik TMP
  hosts: dynamik-tmp
  tasks:
    - ansible.builtin.import_tasks: tasks/dynamik-tmp.yaml

- name: Setup fileseeker
  hosts: fileseeker
  tasks:
    - ansible.builtin.import_tasks: tasks/fileseeker.yaml

- name: Setup csunibo
  hosts: csunibo
  tasks:
    - ansible.builtin.import_tasks: tasks/csunibo.yaml

- name: Setup CSGitBot
  hosts: csgitbot
  tasks:
    - name: Setup csgitbot
      ansible.builtin.import_tasks: tasks/csgitbot.yaml

- name: Setup Homework
  hosts: homework
  tasks:
    - name: Setup Homework
      ansible.builtin.import_tasks: tasks/homework.yaml

- name: Setup CSLogin
  hosts: cslogin
  tasks:
    - name: Setup CSLogin
      ansible.builtin.import_tasks: tasks/cslogin.yaml

- name: Setup Polleg
  hosts: polleg
  tasks:
    - name: Setup Polleg
      ansible.builtin.import_tasks: tasks/polleg.yaml
