- name: Install acl, hugo, lighttpd
  become: true
  ansible.builtin.package:
    name:
      - acl
      - hugo
      - lighttpd
    state: latest
    update_cache: true

- name: Create the cartabinaria user
  become: true
  ansible.builtin.user:
    state: present
    system: true
    name: cartabinaria
    home: /opt/cartabinaria
    shell: /usr/sbin/nologin

- name: Create {{ item }} directory for website
  become: true
  ansible.builtin.file:
    path: /opt/hugo
    state: directory
    owner: cartabinaria
    group: cartabinaria
  with_items: 
    - /opt/hugo
    - /opt/hugo/cartabinaria

- name: Define Go Version
  ansible.builtin.set_fact:
    go_version: 1.20.2

- name: Check if go is installed
  become: true
  ansible.builtin.stat:
    path: /opt/hugo/go
  register: go_installed

- name: Check if go match the required version
  when: go_installed.stat.exists
  block: 
  - name: Get the installed version
    become: true
    ansible.builtin.command: /opt/hugo/go/bin/go version
    register: go_installed_version

  - name: Remove go dir if the version does not match
    when: not go_version in go_installed_version.stdout
    become: true
    ansible.builtin.file:
      path: /opt/hugo/go
      state: absent
  
  - name: Make go reinstall
    when: not go_version in go_installed_version.stdout
    ansible.builtin.set_fact:
      need_to_reinstall_go: true

- name: Install Go Binary
  become: true
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /opt/hugo
    remote_src: true
  when: not go_installed.stat.exists or need_to_reinstall_go|default('false')
  register: go_has_been_reinstalled

- name: Clone cartabinaria website repository
  become: true
  become_user: cartabinaria
  ansible.builtin.git:
    repo: https://github.com/cartabinaria/cartabinaria.github.io
    dest: /opt/hugo/cartabinaria/source
    update: true
    force: yes

- name: Change base url for cartabinaria website
  become: true
  ansible.builtin.lineinfile:
    path: /opt/hugo/cartabinaria/source/config/_default/config.yaml
    regexp: 'baseURL'
    line: "baseURL: '/'"

- name: Remove public directory
  become: true
  ansible.builtin.file:
    path: /opt/hugo/cartabinaria/source/public
    state: absent

- name: Build the cartabinaria website
  become: true
  become_user: cartabinaria
  ansible.builtin.command:
    cmd: hugo
    chdir: /opt/hugo/cartabinaria/source
  environment:
    PATH: "/opt/hugo/go/bin:{{ ansible_env.PATH }}"

- name: Copy lighttpd configuration file
  become: true
  ansible.builtin.copy:
    src: files/cartabinaria/lighttpd.conf
    dest: /etc/lighttpd/lighttpd.conf
    backup: yes

- name: restart lighttpd service
  become: true
  ansible.builtin.service:
    name: lighttpd
    state: restarted
