
- name: Install acl, git, pip, venv
  become: yes
  ansible.builtin.package:
    name:
      - acl 
      - git
      - python3-pip
      - python3-venv
    state: latest
    update_cache: yes

- name: Create the bot user
  become: yes
  ansible.builtin.user:
    state: present
    system: true
    name: bot
    home: /opt/bot
    shell: /usr/sbin/nologin

- name: install wheel
  become: yes
  become_user: bot
  ansible.builtin.pip:
    name: wheel

- name: install pyenv
  become: yes
  become_user: bot
  ansible.builtin.pip:
    name: pyenv

- name: install python 3.10
  become: yes
  become_user: bot
  ansible.builtin.command:
    cmd: pyenv install 3.10

- name: set python 3.10 as local
  become: yes
  become_user: bot
  ansible.builtin.command:
    cmd: pyenv local 3.10

- name: Check if poetry is installed
  become: yes
  ansible.builtin.stat:
    path: /opt/bot/.local/bin/poetry
  register: poetry_installed

- name: Download Poetry Install script
  become: yes
  become_user: bot
  ansible.builtin.get_url:
    url: https://install.python-poetry.org 
    dest: /opt/bot/install-poetry.py
  when: not poetry_installed.stat.exists

- name: Install Poetry Binary
  become: yes
  become_user: bot
  ansible.builtin.command:
    cmd: python3 /opt/bot/install-poetry.py --yes
  when: not poetry_installed.stat.exists

- name: Clone a github repository
  become: yes
  become_user: bot
  ansible.builtin.git:
    repo: "https://github.com/csunibo/csgitbot"
    dest: /opt/bot/source
    version: main
    force: yes
  register: git_result

- name: Install dependencies
  become: yes
  become_user: bot
  ansible.builtin.command:
    cmd: /opt/bot/.local/bin/poetry install
    chdir: /opt/bot/source

- name: Substitute repo owner line in config.init.py
  become: yes
  ansible.builtin.lineinfile:
    path: /opt/bot/source/config.ini
    regexp: '^repo_owner ='
    line: 'repo_owner = csunibo'

- name: Read the bot token
  ansible.builtin.set_fact:
    bot_token: "{{ lookup('file', 'passwords/csgitbot_token') }}"

- name: Copy the systemd service
  become: yes
  ansible.builtin.copy:
    src: files/csgitbot/bot.service
    dest: /etc/systemd/system/bot.service

- name: Copy the env file
  become: yes
  ansible.builtin.template:
    src: files/csgitbot/.env.j2
    dest: /opt/bot/source/.env

- name: Reload the systemd daemon
  become: yes
  ansible.builtin.service:
    daemon_reload: true

- name: Start and enable the bot service
  become: yes
  ansible.builtin.service:
    name: bot 
    state: started 
    enabled: true
  when: not git_result.changed

- name: Restart and enable the bot service
  become: yes
  ansible.builtin.service:
    name: bot 
    state: restarted 
    enabled: true
  when: git_result.changed
    