- name: Define Go Version
  ansible.builtin.set_fact:
    go_version: 1.22.4

- name: Install acl, git
  become: true
  ansible.builtin.package:
    name:
      - acl 
      - git
    state: latest
    update_cache: true

- name: Create the polleg user
  become: true
  ansible.builtin.user:
    state: present
    system: true
    name: polleg
    home: /opt/polleg
    shell: /usr/sbin/nopolleg

- name: Check if go is installed
  become: true
  ansible.builtin.stat:
    path: /opt/polleg/go
  register: go_installed

- name: Check if go match the required version
  when: go_installed.stat.exists
  block: 
  - name: Get the installed version
    become: true
    ansible.builtin.command: /opt/polleg/go/bin/go version
    register: go_installed_version

  - name: Remove go dir if the version does not match
    when: "not 'go_version' in go_installed_version.stdout"
    become: true
    ansible.builtin.file:
      path: /opt/polleg/go
      state: absent
  
  - name: Make go reinstall
    when: "not 'go_version' in go_installed_version.stdout"
    ansible.builtin.set_fact:
      need_to_reinstall_go: true

- name: Install Go Binary
  become: true
  become_user: polleg
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /opt/polleg
    remote_src: true
  when: not go_installed.stat.exists or need_to_reinstall_go|default('false')
  register: go_has_been_reinstalled

- name: Clone a github repository
  become: true
  become_user: polleg
  ansible.builtin.git:
    repo: "https://github.com/cartabinaria/polleg"
    dest: /opt/polleg/source
    version: main
    single_branch: true
  register: git_result

- name: Build polleg
  when: git_result.changed or go_has_been_reinstalled.changed|default('false')
  become: true
  become_user: polleg
  ansible.builtin.shell:
    chdir: /opt/polleg/source
    cmd: /opt/polleg/go/bin/go build -o /opt/polleg/polleg cmd/polleg.go
  register: polleg_has_been_built

- name: Copy the config file
  become: true
  ansible.builtin.template:
    src: files/polleg/config.toml.j2
    dest: /opt/polleg/config.toml

- name: Copy the systemd service
  become: true
  ansible.builtin.template:
    src: files/polleg/polleg.service.j2
    dest: /etc/systemd/system/polleg.service

- name: Reload the systemd daemon
  become: true
  ansible.builtin.service:
    daemon_reload: true

- name: Start and enable the polleg service
  become: true
  ansible.builtin.service:
    name: polleg 
    state: started 
    enabled: true
  when: not git_result.changed

- name: Restart and enable the polleg service
  become: true
  ansible.builtin.service:
    name: polleg 
    state: restarted 
    enabled: true
  when: git_result.changed or polleg_has_been_built.changed|default('false')
