- name: Install fail2ban and ufw
  become: yes
  ansible.builtin.package:
    name:
      - fail2ban
      - ufw
    state: latest

- name: Allow TCP on ssh
  become: true
  community.general.ufw:
    rule: allow
    direction: "{{ item }}"
    port: 2222
    proto: tcp
  loop:
    - "in"
    - "out"

- name: Copy default fail2ban config
  become: yes
  ansible.builtin.copy:
    src: files/security/jail.local
    dest: /etc/fail2ban/jail.local

- name: Enable and start fail2ban and ufw
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - fail2ban
    - ufw

- name: Disable IPv6
  become: True
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: "present"
    reload: "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
